version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: studycafe-postgres
    environment:
      POSTGRES_DB: studycafe
      POSTGRES_USER: studycafe
      POSTGRES_PASSWORD: studycafe
    ports:
      - "5432:5432"
    volumes:
      - studycafe-postgres-data:/var/lib/postgresql/data

volumes:
  studycafe-postgres-data:
